**什么是Pytorch，为什么选择Pytroch？**
在学习python的时候，numpy 就很好用。pytorch是以Python作为开发语言，是一个深度学习的研究平台。Pytorch可以说成Numpy的替代品，因为Pytorch可以使用GPU来更快的运行程序,同时还支持动态神经网络，这是现在很多主流框架比如Tensorflow 等都不支持的。

2. Pytroch的安装, 配置Python环境,准备Python管理器
https://pytorch.org/ 官网 
conda install pytorch torchvision -c pytorch 来安装Pytorch

经常使用python，所以环境都已经安装。比如python,Numpy,Pandas,Matplotlib
Python管理器 是什么意思？我个人是认为 anaconda 管理python 环境的。

3.PyTorch基础概念
pytorch是以Python作为开发语言，是一个深度学习的研究平台。
Numpy matrix - > Ndarrays.    Pytorch matrix -> Tensors.


*PyTorch 的特点：*

支持GPU；
动态神经网络；
Python 优先；
命令式体验；
轻松扩展。

In [2]:
import torch
import numpy as np
arr = [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

通用代码实现流程(实现一个深度学习的代码流程) 这里学习 https://github.com/chenyuntc/pytorch-book/blob/master/chapter2-%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/chapter2:%20PyTorch%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.ipynb 
的autograd: 自动微分。 

PyTorch的autograd模块可以实现了此功能

In [7]:
# 为tensor设置 requires_grad 标识，代表着需要求导数
# pytorch 会自动调用autograd 记录操作
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [8]:
y = x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [9]:
y.grad_fn

In [10]:
y.backward() # 反向传播,计算梯度

In [11]:
# y = x.sum() = (x[0][0] + x[0][1] + x[1][0] + x[1][1])
# 每个值的梯度都为1
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [12]:
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [13]:
y.backward()
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [14]:
x.grad.data.zero_()


tensor([[0., 0.],
        [0., 0.]])

In [15]:
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

神经网络 Neural Network 如何实现。

In [16]:
import torch.nn as nn
import torch.nn.functional as F

In [17]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # 卷积层 '1'表示输入图片为单通道, '6'表示输出通道数，'5'表示卷积核为5*5
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
